/**
 * Sports Page E2E Tests
 *
 * Tests run against the LIVE production site: https://streamvault.srinivaskotha.uk
 * All API calls hit the real backend — no mocking.
 * Uses Playwright global storageState (via global-setup.ts) for authentication.
 *
 * DOM Facts (verified from SportsPage.tsx source, 2026-04-08):
 * - Page heading: h1 "Sports"
 * - All chip: [data-focus-key="sports-chip-all"]
 * - Category chips: [data-focus-key^="sports-chip-"] (excludes "sports-chip-all")
 * - Search input: input[placeholder*="Search sports"]
 * - Channel cards: [data-focus-key^="sports-"] (channel id suffix)
 * - Empty state when no channels: visible heading "No sports channels" or "No matching channels"
 *
 * Generated by playwright-pro skill (SRI-170 smoke test, 2026-04-08).
 * Coverage: Sports page load, category filter chips, search filter, empty state.
 */

import { test, expect } from "@playwright/test";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

async function goToSports(page: import("@playwright/test").Page) {
  await page.goto("/sports");
  await page.waitForLoadState("domcontentloaded");
  // Wait for React hydration + first API response
  await page.waitForTimeout(3_000);
}

// ---------------------------------------------------------------------------
// Sports Page
// ---------------------------------------------------------------------------

test.describe("Sports page", () => {
  test.beforeEach(async ({ page }) => {
    await goToSports(page);
  });

  test("loads with Sports heading", async ({ page }) => {
    await expect(
      page.getByRole("heading", { name: "Sports", level: 1 }),
    ).toBeVisible();
  });

  test("shows either channel content or empty state — not a blank screen", async ({
    page,
  }) => {
    // One of these must be visible: content rail, channel card, skeleton (loading),
    // or empty state — never just a blank container
    const contentPresent =
      (await page.locator('[data-focus-key^="sports-"]').count()) > 0 ||
      (await page
        .getByRole("heading", { name: /No sports channels/i })
        .isVisible()
        .catch(() => false));

    expect(contentPresent).toBe(true);
  });

  test("All chip is visible and active by default", async ({ page }) => {
    const allChip = page.locator('[data-focus-key="sports-chip-all"]');
    // Chip is present only when there are multiple categories; skip if absent
    if ((await allChip.count()) === 0) {
      test.skip();
      return;
    }
    await expect(allChip).toBeVisible();
    // Active chip has the teal border class applied in SportsPage.tsx
    await expect(allChip).toHaveClass(/text-teal/);
  });

  test("category chips are visible when categories exist", async ({ page }) => {
    const chips = page.locator('[data-focus-key^="sports-chip-"]');
    const count = await chips.count();
    if (count === 0) {
      test.skip();
      return;
    }
    // At minimum the "all" chip must be visible
    await expect(chips.first()).toBeVisible();
  });

  test("clicking a category chip filters the channel list", async ({
    page,
  }) => {
    // Need at least one non-all chip
    const categoryChips = page.locator(
      '[data-focus-key^="sports-chip-"]:not([data-focus-key="sports-chip-all"])',
    );
    const count = await categoryChips.count();
    if (count === 0) {
      test.skip();
      return;
    }

    const firstChip = categoryChips.first();
    const chipLabel = await firstChip.textContent();

    // Record count before filtering
    const beforeCount = await page
      .locator('[data-focus-key^="sports-"]')
      .count();

    await firstChip.click();
    // Wait for filter to apply
    await page.waitForTimeout(500);

    // After clicking a specific category chip, All chip should no longer be
    // the active one (class change), and the channel count may differ
    const allChip = page.locator('[data-focus-key="sports-chip-all"]');
    // allChip loses teal border when a category is selected
    await expect(allChip).not.toHaveClass(/bg-teal\/15/);

    // Chip we clicked should now be active
    await expect(firstChip).toHaveClass(/bg-teal\/15/);

    // Result count label is shown when filters are active
    const resultLabel = page.locator("p").filter({ hasText: /channel/ });
    await expect(resultLabel.first()).toBeVisible();

    void chipLabel; // used for test readability above
    void beforeCount;
  });

  test("search input is present and accepts text", async ({ page }) => {
    const searchInput = page.locator('input[placeholder*="Search sports"]');
    if ((await searchInput.count()) === 0) {
      test.skip();
      return;
    }

    await expect(searchInput).toBeVisible();
    await searchInput.fill("cricket");
    await expect(searchInput).toHaveValue("cricket");
  });

  test("search with non-matching query shows empty state", async ({ page }) => {
    const searchInput = page.locator('input[placeholder*="Search sports"]');
    if ((await searchInput.count()) === 0) {
      test.skip();
      return;
    }

    // Use a search string extremely unlikely to match any real channel
    await searchInput.fill("xyzzy_no_match_8675309");
    // Debounce is 300 ms — wait for filter to apply
    await page.waitForTimeout(600);

    await expect(
      page.getByRole("heading", { name: /No matching channels/i }),
    ).toBeVisible();
  });

  test("clearing search restores full channel list", async ({ page }) => {
    const searchInput = page.locator('input[placeholder*="Search sports"]');
    if ((await searchInput.count()) === 0) {
      test.skip();
      return;
    }

    await searchInput.fill("xyzzy_no_match_8675309");
    await page.waitForTimeout(600);

    // Clear via the X button rendered when input has a value
    const clearBtn = page.locator(
      'button[aria-label="Clear search"], button:near(input[placeholder*="Search sports"])',
    );
    if ((await clearBtn.count()) > 0) {
      await clearBtn.first().click();
    } else {
      await searchInput.fill("");
    }

    await page.waitForTimeout(600);

    // Empty-state heading should be gone
    await expect(
      page.getByRole("heading", { name: /No matching channels/i }),
    ).not.toBeVisible();
  });
});
